FROM node:14-alpine
WORKDIR /app

COPY package.json package-lock.json ./

RUN echo "📄 Conteúdo do package.json:" && cat package.json
RUN echo "📄 Conteúdo do package-lock.json:" && cat package-lock.json
